# Translations template for invenio-oauthclient.
# Copyright (C) 2025 CERN
# This file is distributed under the same license as the invenio-oauthclient
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
# 
# Translators:
# Tibor Simko <tibor.simko@cern.ch>, 2021
# Bessem Aamira <bessemamira@gmail.com>, 2025
# Salaheddine Ben Ali <salaheddine.benali@cnudst.tn>, 2025
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: invenio-oauthclient 4.1.4\n"
"Report-Msgid-Bugs-To: info@inveniosoftware.org\n"
"POT-Creation-Date: 2025-03-27 15:00+0000\n"
"PO-Revision-Date: 2016-08-18 15:19+0000\n"
"Last-Translator: Salaheddine Ben Ali <salaheddine.benali@cnudst.tn>, 2025\n"
"Language-Team: Arabic (https://app.transifex.com/inveniosoftware/teams/23537/ar/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"
"Language: ar\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"

#: invenio_oauthclient/admin.py:54
msgid "ID"
msgstr "معرّف"

#: invenio_oauthclient/admin.py:55
msgid "User ID"
msgstr "معرّف المستخدم"

#: invenio_oauthclient/admin.py:56
msgid "Client ID"
msgstr "معرّف حريف"

#: invenio_oauthclient/admin.py:85
msgid "ID Remote Account"
msgstr "معرّف حساب خارجي"

#: invenio_oauthclient/admin.py:92 invenio_oauthclient/admin.py:100
msgid "User Management"
msgstr "إدارة المستخدم"

#: invenio_oauthclient/admin.py:93 invenio_oauthclient/ext.py:260
#: invenio_oauthclient/templates/invenio_oauthclient/settings/index.html:12
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html:12
msgid "Linked accounts"
msgstr "الحسابات المرتبطة"

#: invenio_oauthclient/admin.py:101
msgid "Linked account tokens"
msgstr "الرموز المميزة للحساب المرتبط"

#: invenio_oauthclient/ext.py:250
#, python-format
msgid "%(icon)s Linked accounts"
msgstr "%(icon)s حسابات مرتبطة"

#: invenio_oauthclient/contrib/cern.py:410
#, python-format
msgid "Identity class %(identity_class)s is not one of [%(valid_identities)s]"
msgstr ""
"فئة الهوية Identity class %(identity_class)s ليست واحدة من "
"[%(valid_identities)s]"

#: invenio_oauthclient/contrib/cern.py:441
#: invenio_oauthclient/contrib/cern_openid.py:305
msgid "CERN account not allowed."
msgstr " حساب CERN غير مسموح به."

#: invenio_oauthclient/contrib/cern_openid.py:278
#, python-format
msgid "User roles %(cern_roles)s are not one of %(valid_roles)s"
msgstr "أدوار المستخدم %(cern_roles)s ليست واحدة من %(valid_roles)s"

#: invenio_oauthclient/contrib/github.py:109
msgid "GitHub"
msgstr "جيت هوب GitHub"

#: invenio_oauthclient/contrib/github.py:110
msgid "Software collaboration platform."
msgstr "منصة تعاون للبرمجة."

#: invenio_oauthclient/contrib/github.py:265
#: invenio_oauthclient/contrib/github.py:287
msgid "Application mis-configuration in GitHub"
msgstr "خطأ في تثبيت إعدادات التطبيق في GitHub"

#: invenio_oauthclient/contrib/globus.py:95
msgid "Globus"
msgstr "غلوبس Globus"

#: invenio_oauthclient/contrib/globus.py:96
msgid "Research data management simplified."
msgstr "إدارة بيانات البحث مبسّطة."

#: invenio_oauthclient/contrib/globus.py:168
msgid "Application mis-configuration in Globus"
msgstr "خطأ في تثبيت إعدادات التطبيق في Globus"

#: invenio_oauthclient/contrib/globus.py:203
msgid "Failed to fetch user id, likely server mis-configuration"
msgstr "فشل جلب معرف id المستخدم، ربما يكون هناك خطأ في تثبيت إعدادات الموزّع"

#: invenio_oauthclient/contrib/openaire_aai.py:105
#: invenio_oauthclient/contrib/openaire_aai.py:170
msgid "OpenAIRE"
msgstr "OpenAIRE"

#: invenio_oauthclient/contrib/openaire_aai.py:106
#: invenio_oauthclient/contrib/openaire_aai.py:171
msgid "Open Science Services."
msgstr "خدمات العلم المفتوح."

#: invenio_oauthclient/contrib/orcid.py:113
msgid "ORCID"
msgstr "أوركيد ORCID"

#: invenio_oauthclient/contrib/orcid.py:114
msgid "Connecting Research and Researchers."
msgstr "ربط التواصل بين البحث والباحثين."

#: invenio_oauthclient/contrib/keycloak/helpers.py:32
#, python-format
msgid ""
"Invalid app name %(app_name)s. It should only contain letters, numbers, "
"dashes and underscores"
msgstr ""
"اسم التطبيق غير صالح %(app_name)s. يجب أن يحتوي على أحرف وأرقام وشرطات "
"وشرطات سفلية فقط."

#: invenio_oauthclient/handlers/rest.py:91
#: invenio_oauthclient/handlers/token.py:71
#: invenio_oauthclient/handlers/ui.py:242
msgid "Authorization with remote service failed."
msgstr "فشل الإذن بالخدمة عن بعد."

#: invenio_oauthclient/handlers/rest.py:99
#: invenio_oauthclient/handlers/ui.py:65
msgid "You rejected the authentication request."
msgstr "لقد رفضت طلب المصادقة."

#: invenio_oauthclient/handlers/rest.py:103
#: invenio_oauthclient/handlers/ui.py:60
msgid "External service is already linked to another account."
msgstr "الخدمة الخارجية مرتبطة حاليا مع حساب أخر."

#: invenio_oauthclient/handlers/rest.py:113
msgid "Unauthorized."
msgstr "غير مرخّص"

#: invenio_oauthclient/handlers/rest.py:120
#: invenio_oauthclient/handlers/rest.py:290
msgid "Successfully signed up."
msgstr "تم التسجيل بنجاح."

#: invenio_oauthclient/handlers/rest.py:129
msgid "Token not found."
msgstr "الرمز Token غير موجود"

#: invenio_oauthclient/handlers/rest.py:136
msgid "Could not create token for user."
msgstr "لم يتمكن من إنشاء رمز token للمستخدم."

#: invenio_oauthclient/handlers/rest.py:216
msgid "Successfully authorized."
msgstr "تمت الموافقة على الإذن بنجاح."

#: invenio_oauthclient/handlers/rest.py:246
msgid "Successfully disconnected."
msgstr "تم قطع الاتصال بنجاح."

#: invenio_oauthclient/handlers/token.py:62
msgid "User rejected request."
msgstr "تم رفض الطلب من قبل المستخدم."

#: invenio_oauthclient/handlers/token.py:75
msgid "Bad OAuth authorized request"
msgstr "طلب تفويض OAuth غير صالح"

#: invenio_oauthclient/handlers/ui.py:157
#, python-format
msgid ""
"A confirmation email has already been sent to %(email)s. Didn't receive it? "
"Click <strong><a href=\"%(url)s\">here</a></strong> to resend it."
msgstr ""
"تم إرسال رسالة تأكيد إلى %(email)s. إن لم تستلمها؟ انقر <strong><a "
"href=\"%(url)s\">هنا</a></strong> لإعادة إرسالها."

#: invenio_oauthclient/handlers/utils.py:126
#, python-format
msgid ""
"Error while syncing roles: A managed role with id: %(group_id)s already "
"exists"
msgstr ""
"حدث خطأ أثناء مزامنة الأدوار: يوجد دور بصدد الإدارة يحمل المعرف id: "
"%(group_id)sبالفعل"

#: invenio_oauthclient/handlers/utils.py:136
#, python-format
msgid ""
"Error while syncing roles: A managed role with name: %(group_name)s already "
"exists"
msgstr ""
"حدث خطأ أثناء مزامنة الأدوار: يوجد دور بصدد الإدارة يحمل إسم: %(group_name)s"
" بالفعل"

#: invenio_oauthclient/templates/invenio_oauthclient/_macros.html:25
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/_macros.html:60
#, python-format
msgid "Sign in with %(title)s"
msgstr "الاشتراك مع %(title)s"

#: invenio_oauthclient/templates/invenio_oauthclient/login_user.html:21
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html:26
msgid "OR"
msgstr "أو"

#: invenio_oauthclient/templates/invenio_oauthclient/signup.html:24
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/signup.html:29
#, python-format
msgid "Sign-up with %(title)s!"
msgstr "الاشتراك مع %(title)s!"

#: invenio_oauthclient/templates/invenio_oauthclient/signup.html:25
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/signup.html:32
msgid ""
"Fill in your details to complete your registration. You only have to do this"
" once."
msgstr "املأ بياناتك لإكمال تسجيلك. ما عليك سوى القيام بذلك مرة واحدة."

#: invenio_oauthclient/templates/invenio_oauthclient/signup.html:33
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/signup.html:45
msgid "Complete registration"
msgstr "أتمم التسجيل"

#: invenio_oauthclient/templates/invenio_oauthclient/settings/index.html:20
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html:21
#, python-format
msgid ""
"Tired of entering password for %(sitename)s every time you sign in? Set up "
"single sign-on with one or more of the services below:"
msgstr ""
"هل سئمت تكرار إدخال كلمة المرور عند تسجيل الدخول في %(sitename)s؟ قم بإعداد "
"تسجيل الدّخول مرّة واحدة في خدمة او خدمات أسفله:"

#: invenio_oauthclient/templates/invenio_oauthclient/settings/index.html:31
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html:53
msgid "Disconnect"
msgstr "قطع الاتصال"

#: invenio_oauthclient/templates/invenio_oauthclient/settings/index.html:33
#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/settings/index.html:62
msgid "Connect"
msgstr "قم بالتوصيل"

#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html:39
msgid "Forgot password?"
msgstr "فقدت كلمة المرور؟"

#: invenio_oauthclient/templates/semantic-ui/invenio_oauthclient/login_user.html:45
msgid "Resend confirmation email"
msgstr "أعد إرسال تأكيد البريد الإلكتروني"
